security:
  oauth2:
    client:
     client-id: -insert here-
     client-secret: -insert here-
     access-token-uri: https://graph.facebook.com/oauth/access_token
     user-authorization-uri: https://www.facebook.com/dialog/oauth
     authentication-scheme: query
     client-authentication-scheme: form
    resource:
     user-info-uri: https://graph.facebook.com/me